### ISSUE TITLE
Improve visibility for colourblind people

### ISSUE THREAD

**Issue by microbialme** [GraphicsPrinciples/CheatSheet#1]
Hi there!
A suggestion to improve your next poster version would be to provide explicit instructions on how to improve visibility of graphics for colourblind people. It would be great to see this become standard practice for the graphics community

**Comment by baillma3** [comment]
Hi, thank you for the very relevant suggestion. It is something we have considered as a team but did not make it explicit in this version of the cheat sheet. We are currently writing a tutorial based on this work. I think this is a great topic to consider both in terms of who the potential audience is and also the use of color. Thank you for raising it.
